version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: entreprise_events_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: entreprise_events_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events_db
      MYSQL_USER: event_user
      MYSQL_PASSWORD: event_pass
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: entreprise_events_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge